import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class DashboardScreen extends StatefulWidget { const DashboardScreen({super.key}); @override State<DashboardScreen> createState()=>_DashboardScreenState(); }
class _DashboardScreenState extends State<DashboardScreen>{ int index=0; @override Widget build(BuildContext context){ final pages=[const Overview(), const Controls(), const Reports(), const Alerts()]; return Scaffold(appBar:AppBar(title:const Text('Guardian Parent'),actions:[IconButton(onPressed:()=>context.go('/settings'),icon:const Icon(Icons.settings))]), body:pages[index], floatingActionButton:FloatingActionButton.extended(onPressed:()=>context.go('/pair'),icon:const Icon(Icons.qr_code),label:const Text('Pair child')), bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const [NavigationDestination(icon:Icon(Icons.dashboard),label:'Home'),NavigationDestination(icon:Icon(Icons.tune),label:'Controls'),NavigationDestination(icon:Icon(Icons.bar_chart),label:'Reports'),NavigationDestination(icon:Icon(Icons.notifications),label:'Alerts')]));}}
class Overview extends StatelessWidget{ const Overview({super.key}); @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:const [_Hero(), _MetricGrid(), ListTile(leading:Icon(Icons.child_care),title:Text('No child devices yet'),subtitle:Text('Pair with an invite code or QR code. Parent approval is always required.'))]);}
class _Hero extends StatelessWidget{ const _Hero(); @override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Everything you need to keep them safe, all in one place.',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),const Text('Monitor device health, screen time, location safety zones, and app rules with clear consent.')]))) ;}
class _MetricGrid extends StatelessWidget{ const _MetricGrid(); @override Widget build(BuildContext context){ const items={'Devices':'0','Screen time':'--','Alerts':'0','Online':'--'}; return GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),childAspectRatio:2.1,children:items.entries.map((e)=>Card(child:Center(child:ListTile(title:Text(e.value,style:Theme.of(context).textTheme.headlineSmall),subtitle:Text(e.key))))).toList());}}
class Controls extends StatelessWidget{ const Controls({super.key}); @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:['Daily device time limit','Weekly schedule','School mode','Study mode','Bedtime mode','Block applications','Website filtering','Remote ringtone','Lock device schedule'].map((t)=>SwitchListTile(value:false,onChanged:(_){},title:Text(t))).toList());}
class Reports extends StatelessWidget{ const Reports({super.key}); @override Widget build(BuildContext context)=>const Center(child:Text('Daily, weekly, and monthly analytics charts appear after a child device is paired.'));}
class Alerts extends StatelessWidget{ const Alerts({super.key}); @override Widget build(BuildContext context)=>const Center(child:Text('Notifications: new app, offline, battery low, geofence, restricted app, permission changes.'));}
